config/routes.rb
Project::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :a_classes, only: [:new, :create, :destroy, :show]
  resources :tasks, only: [:create, :destroy]
  root 'welcome_pages#welcome' 
    
  get '/addclass' => 'a_classes#new'
  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'    
  get '/about' => 'welcome_pages#about'
  get '/welcome' => 'welcome_pages#welcome'
  get '/help' => 'welcome_pages#help'

    

end

app/models/a_class.rb
class AClass < ActiveRecord::Base
    belongs_to :user
    has_many :tasks, dependent: :destroy
    
    validates :name, presence: true, length: { maximum: 40 }
    validates :user_id, presence: true
    
end

app/models/task.rb
class Task < ActiveRecord::Base
    belongs_to :a_class
    default_scope -> { order('"dueDate" ASC') }
    validates :a_class_id, presence: true
    validates :name, presence: true, length: { maximum: 50 }
    validates :description, length: { maximum: 50 }
    
    VALID_DATE_REGEX = /\d{4}+[-]+\d{2}+[-]+\d{2}/
    validates :dueDate, format: { with: VALID_DATE_REGEX }
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :a_classes
    before_save { self.email = email.downcase }
    before_create :create_remember_token
    
    validates :name, presence: true, length: { maximum: 25 }
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    
    has_secure_password
    validates:password, length: { minimum: 6 }

    def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/a_classes_controller.rb
class AClassesController < ApplicationController
    before_action :signed_in_user
    before_action :correct_user, only: [:destroy, :show]
    
    def show
        @a_class = AClass.find(params[:id])
        @tasks = @a_class.tasks.paginate(page: params[:page])
        @task = @a_class.tasks.build if signed_in?
    end
    
    def new
        @a_class = current_user.a_classes.build if signed_in?
    end
    
    def create
        @a_class = current_user.a_classes.build(a_class_params)
        if @a_class.save
            flash[:success] = "Class added"
            redirect_to current_user
        else
            render 'a_classes/new'
        end
    end
    
    def destroy
        @a_class.destroy
        redirect_to current_user
    end
    
    private
    
        def a_class_params
            params.require(:a_class).permit(:name)
        end
    
    def correct_user
        @a_class = current_user.a_classes.find_by(id: params[:id])
        redirect_to root_url if @a_class.nil?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

   def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user, only: :destroy

  def create
     
      @task = $current_class.tasks.build(task_params)
      if @task.save
          flash[:success] = "Task added"
          redirect_to $current_class
      else
          redirect_to $current_class
      end
  end
    

  def destroy
      @task.destroy
      flash[:success] = "Congratulations! You have completed an assignment!"
      redirect_to $current_class
  end
    
  private
    def task_params
        params.require(:task).permit(:name, :description, :dueDate)
    end
    
    def correct_user
        @task = $current_class.tasks.find_by(id: params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update, :show]
    
  def show
        @a_classes = @user.a_classes.paginate(page: params[:page])
  end
    
  def new
      @user = User.new
  end
    
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Life Tracker!"
      redirect_to @user
    else
      render 'new'
    end
  end
    
    def edit
    end
    
   def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
    
    
    private
    
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    #before filters
    
    def signed_in_user
        redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(signin_path) unless current_user?(@user)
    end
end

app/controllers/welcome_pages_controller.rb
class WelcomePagesController < ApplicationController
  def welcome
  end

  def about
  end

  def help
  end
end

app/helpers/a_classes_helper.rb
module AClassesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

     def signed_in?
    !current_user.nil?
  end
    
    def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end
    
def signed_in_user
    unless signed_in?
      redirect_to signin_url, notice: "Please sign in."
    end
  end
    
    def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
    
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/helpers/welcome_pages_helper.rb
module WelcomePagesHelper
end

app/views/a_classes/_a_class.html.erb
<li>
    <span class="content"><span class="className"><%= a_class.name%>
    <% @pending = a_class.tasks.count.to_s + " pending tasks" %>
    <span class="taskLink"><%= link_to @pending, a_class %></span></span>
    
    <section class="removeClass">
        <%= link_to "remove", a_class, method: :delete, data: { confirm: "Are you sure?" }, title: a_class.name %>
    </section>
</li>

app/views/a_classes/new.html.erb
<%= form_for(@a_class) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    
    <%= f.text_area :name, placeholder: "The name of the class..." %>
  </div>
  <%= f.submit "Add class", class: "btn btn-large btn-primary" %>
<% end %>

app/views/a_classes/show.html.erb
<% provide(:title, @a_class.name) %>
 <div class="row">
    <aside class="span4">
        <section>
            <h2><b><%= @a_class.name %></b></h2>
            <p><h3>Add a new task to the list</h3></p>
        </section>
    
        <section>
            <% $current_class = @a_class %>
            <%= render 'shared/task_form' %>
        </section>
    </aside>
    <div class="span8">
        <h2>Tasks (<%= @a_class.tasks.count %>)</h2>
        
        <ol class="tasks">
            <%= render @tasks %>
        </ol>
        <%= will_paginate @tasks %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        
            
              <% if signed_in? %>
              <div class="container">
          <%= link_to "life tracker", current_user, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
            
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
          <div class="container">
          <%= link_to "life tracker", welcome_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Life Tracker | <%= yield(:title) %></title>
        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>
    </head>
    
    <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
      <%= render 'layouts/footer' %>

    </body>  
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_task_form.html.erb
<%= form_for(@task) do |f| %>
 <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :name, placeholder: "Assigment name..." %>
  </div>
  <div class="field">
    <%= f.text_area :description, placeholder: "Description of assignment...(50 characters max)" %>
  </div>
  <div class= "field">
    <%= f.text_area :dueDate, placeholder: "Date Due, format: YYYY-MM-DD" %>
  </div>
  <%= f.submit "Add task", class: "btn btn-large btn-primary" %>
<% end %>

app/views/tasks/_task.html.erb
<li>
  <span class="name"><%= task.name %>
  <span class="dueDate"> Due on: <%= task.dueDate.strftime("%B %d, %Y") %>
  </span></span>
  <span class="description"><%= task.description %></span>
  
  <span class="completed">
  <%= link_to "Completed", task, method: :delete,
                                     data: { confirm: "Is the assignment complete?" },
                                     title: task.name %>
  </span>
</li> 

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="span4">
        <section>
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
    <div class="span8">
        <% if @user.a_classes.any? %>
        <section class="classtitle">
        <p>Classes</p>
        </section>
            <ol class="a_classes">
            <%= render @a_classes %>
            </ol>
            <%= will_paginate @a_classes %>
        <% end %>
        <%= link_to "Add a class", addclass_path, class: "btn btn-large btn-primary"%>
    </div>
</div>

app/views/welcome_pages/about.html.erb
<% provide(:title, 'About') %>

<div class="hero-unit">
    <section class="about">
    <h1>About Life Tracker</h1>
    <section class="info">
    <h2>What is Life Tracker?</h2>
    <p>As a college student I don't always do a great job keeping track of everything going on in my life, especially homework, so I decided to create a web app so I could keep track of it from wherever I was.</p>
    <h2>How do you use Life Tracker?</h2>
    <p>To start tracking your homework, all you have to do is make an account, add a class to your class list and then begin tracking the assignments you have due.</p>
    </section>
    </section>
</div>

 

app/views/welcome_pages/help.html.erb
<% provide(:title, 'Help') %>

<div class="center hero-unit">
    <h1>Help</h1>
    <h2>Having trouble with the page? Send me an email at rlorenz@wisc.edu</h2>
</div>

app/views/welcome_pages/welcome.html.erb
<% provide(:title, 'Welcome') %>
<div class="center hero-unit">
    <h1>Welcome to Life Tracker</h1>

    <h2>New to being organized?</h2>
    
    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
    
<h3> 
Already have an account?
    <%= link_to "Sign in", signin_path %>
</h3>